flowchart TD

    %% Nodes
        StartPoint(登入流程開始)
        EndPoint(登入流程結束)
        ReceiveInformation(接收使用者資訊)
        ValidateInformation{驗證使用者資訊}
        IsForceLogout{是否強制登出}
        CheckSessionKeyFromRedis{檢查使用者登入Session是否存在}
        ReturnForceLogout(回傳強制登出訊息)
        DeleteSessionFromRedis(刪除使用者登入Session)
        ProduceSession(產生登入Session)
        StoreSessionInRedis(將登入Session存入Redis)
        ReturnError(回傳登入失敗訊息)

    %% Flow
    StartPoint --> ReceiveInformation
    ReceiveInformation --> ValidateInformation
    ValidateInformation --> |資訊驗證通過| IsForceLogout
    IsForceLogout --> |是| DeleteSessionFromRedis
    IsForceLogout --> |否| CheckSessionKeyFromRedis
    CheckSessionKeyFromRedis --> |Session存在| ReturnForceLogout
    CheckSessionKeyFromRedis --> |Session不存在| ProduceSession
    ReturnForceLogout --> EndPoint
    DeleteSessionFromRedis --> ProduceSession
    ProduceSession --> StoreSessionInRedis
    StoreSessionInRedis --> EndPoint
    ValidateInformation --> |資訊驗證失敗| ReturnError
    ReturnError --> EndPoint