from pathlib import Path


def test_product_and_label_ddl_match_required_key_types() -> None:
    products = Path("database/DDL/tables/TB_PRODUCTS.sql").read_text(
        encoding="utf-8",
    )
    labels = Path("database/DDL/tables/TB_LABELS.sql").read_text(
        encoding="utf-8",
    )

    assert "id VARCHAR(13) PRIMARY KEY" in products
    assert "label_ids TEXT NOT NULL" in products
    assert "delete_flag BOOLEAN NOT NULL DEFAULT FALSE" in products
    assert "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in labels
