CREATE TABLE tb_labels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_uid VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_uid VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

COMMENT ON TABLE tb_labels IS 'Product label records';
COMMENT ON COLUMN tb_labels.id IS 'Label ID';
COMMENT ON COLUMN tb_labels.name IS 'Label name';
COMMENT ON COLUMN tb_labels.created_uid IS 'Creator UID';
COMMENT ON COLUMN tb_labels.created_at IS 'UTC creation timestamp';
COMMENT ON COLUMN tb_labels.updated_uid IS 'Last updater UID';
COMMENT ON COLUMN tb_labels.updated_at IS 'UTC last-update timestamp';
