CREATE TABLE tb_labels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_uid VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_uid VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

COMMENT ON TABLE tb_labels IS '產品標籤資料';
COMMENT ON COLUMN tb_labels.id IS '標籤識別碼';
COMMENT ON COLUMN tb_labels.name IS '標籤名稱';
COMMENT ON COLUMN tb_labels.created_uid IS '建立者 UID';
COMMENT ON COLUMN tb_labels.created_at IS '建立時間';
COMMENT ON COLUMN tb_labels.updated_uid IS '最後更新者 UID';
COMMENT ON COLUMN tb_labels.updated_at IS '最後更新時間';
